### ISSUE TITLE
Chart not showing up

### ISSUE THREAD

**Issue by trsigg** [dkthehuman/webtimer#10]
Recently the chart in the popup window has stopped appearing. From the console errors it looks as though the error is coming from the Google Charts library (https://www.google.com/jsapi) failing to load. Here's the first error that shows up in my console:

>Refused to load the script 'https://www.gstatic.com/charts/loader.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://www.google.com https://platform.twitter.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by POPOBE97** [comment]
> Recently the chart in the popup window has stopped appearing. From the console errors it looks as though the error is coming from the Google Charts library (https://www.google.com/jsapi) failing to load. Here's the first error that shows up in my console:
> 
> > Refused to load the script 'https://www.gstatic.com/charts/loader.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://www.google.com https://platform.twitter.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Having the same problem here.

**Comment by POPOBE97** [comment]
> Recently the chart in the popup window has stopped appearing. From the console errors it looks as though the error is coming from the Google Charts library (https://www.google.com/jsapi) failing to load. Here's the first error that shows up in my console:
> 
> > Refused to load the script 'https://www.gstatic.com/charts/loader.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://www.google.com https://platform.twitter.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Fixed. See pull request.

**Comment by dkthehuman** [comment]
Hey Tynan, thanks for the report! Sorry it took so long for the fix — have been focusing on other projects and haven't had much time to look at this.

I fixed the issue and submitted the updated version to the Chrome Web Store, so it should start working in the next several days. Thanks!
